### ISSUE TITLE
Can't reach the end of the scrolling area via scroll bar

### ISSUE THREAD

**Issue by sarbbottam** [tbranyen/hyperlist#5] opened 2016-05-11 06:03 UTC
Please refer the attached gif, not sure if that's a valid use case for `hyperlist`. I am sure `2 million` recod is not a practical scenario, but I guess, I should be able to reach the end of the list via scroll bar.

![hyperlist](https://cloud.githubusercontent.com/assets/949380/15171420/3757696a-1703-11e6-8c87-9aaf492be759.gif)

**Comment by tbranyen** [comment] 2016-05-11 06:40
Weird I'll have to test on a Mac tomorrow, works fine in Linux Chrome. I can reach it with the scrollbar, page down, and the touch pad.

**Comment by tbranyen** [comment] 2017-05-01 16:03
Closing this out since it's an older issue and can't reproduce.

**Closed by tbranyen** 2017-05-01 16:03 UTC
